development:
  adapter: postgresql
  encoding: utf8
  database: onleague_development
  pool: 5
  username: onLeague

test:
  adapter: postgresql
  encoding: utf8
  database: onleague_test
  pool: 5
  username: postgres